pharma_dashboard/urls.py
from django.conf import settings
from django.urls.conf import path, include, re_path
from edc_dashboard import UrlConfig

from .views import ListboardView, DispensaryListboardView, DispensePrintActionsView
from .views import ReportListboardView, StockListboardView
from .patterns import subject_identifier

app_name = 'pharma_dashboard'

patient_listboard_url_config = UrlConfig(
    url_name='patient_listboard_url',
    view_class=ListboardView,
    label='patient_listboard',
    identifier_label='subject_identifier',
    identifier_pattern=None)

dispense_listboard_url_config = UrlConfig(
    url_name='dispense_listboard_url',
    view_class=DispensaryListboardView,
    label='dispense_listboard',
    identifier_label='subject_identifier',
    identifier_pattern=subject_identifier)

stock_listboard_url_config = UrlConfig(
    url_name='stock_management_listboard_url',
    view_class=StockListboardView,
    label='stock_management_listboard',
    identifier_label='stock_id',
    identifier_pattern='')

report_listboard_url_config = UrlConfig(
    url_name='report_listboard_url',
    view_class=ReportListboardView,
    label='report_listboard',
    identifier_label='code',
    identifier_pattern='')


urlpatterns = [re_path(r'^dispense_print/'
                       '(?P<subject_identifier>[-\w]+)/'
                       '(?P<dispense_pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/$',
                       DispensePrintActionsView.as_view(),
                       name='print_url'), ]
urlpatterns += patient_listboard_url_config.listboard_urls
urlpatterns += dispense_listboard_url_config.listboard_urls
urlpatterns += stock_listboard_url_config.listboard_urls
urlpatterns += report_listboard_url_config.listboard_urls

if settings.APP_NAME == 'pharma_dashboard':

    from django.views.generic.base import RedirectView

    urlpatterns += [
        path('accounts/', include('edc_base.auth.urls')),
        path('edc_data_manager/', include('edc_data_manager.urls')),
        path('edc_device/', include('edc_device.urls')),
        path('edc_protocol/', include('edc_protocol.urls')),
        path('admininistration/', RedirectView.as_view(url='admin/'),
             name='administration_url'),
        path(r'', RedirectView.as_view(url='admin/'), name='home_url')]

pharma_dashboard/views/dispense_print_actions_view.py
from django.conf import settings
from django.contrib import messages
from django.views.generic.edit import ProcessFormView
from django.views.generic.base import TemplateView
from edc_base.view_mixins import EdcBaseViewMixin
from edc_label.job_result import JobResult
from edc_label.printers_mixin import PrintersMixin

from ..prescription_labels import PrescriptionLabels


class DispensePrintActionsView(EdcBaseViewMixin, PrintersMixin,
                               TemplateView, ProcessFormView):

    job_result_cls = JobResult
    template_name = 'pharma_dashboard/subject_record.html'
    prescription_labels_cls = PrescriptionLabels
    success_url = settings.DASHBOARD_URL_NAMES.get('dispense_listboard_url')
    print_selected_button = 'print_selected_labels'
    print_all_button = 'print_all_labels'
    print_prescription = 'print_prescription'
    checkbox_name = 'selected_presciption_names'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if kwargs.get('dispense_pk'):
            self.print_labels_action(dispense_pk=kwargs.get('dispense_pk'))
        return context

    def print_labels_action(self, dispense_pk=None):
        labels = self.prescription_labels_cls(
            dispense_pk=self.kwargs.get('dispense_pk'),
            user=self.request.user)

        if labels.zpl_data:
            job_id = self.clinic_label_printer.stream_print(
                zpl_data=labels.zpl_data)
            job_result = self.job_result_cls(
                name=labels.label_template_name, copies=1, job_ids=[job_id],
                printer=self.clinic_label_printer)
            messages.success(self.request, job_result.message)

pharma_dashboard/views/listboard_view.py
import re

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.utils.decorators import method_decorator
from edc_base.view_mixins import EdcBaseViewMixin
from edc_dashboard.view_mixins import ListboardFilterViewMixin, SearchFormViewMixin
from edc_dashboard.views import ListboardView
from edc_navbar import NavbarViewMixin

from ..model_wrappers import PatientModelWrapper


class ListboardView(NavbarViewMixin, EdcBaseViewMixin,
                    ListboardFilterViewMixin, SearchFormViewMixin,
                    ListboardView):

    listboard_template = 'patient_listboard_template'
    listboard_url = 'patient_listboard_url'
    listboard_panel_style = 'success'
    listboard_fa_icon = 'fa-user-plus'

    model = 'pharma_subject.patient'
    model_wrapper_cls = PatientModelWrapper
    navbar_name = 'pharma_dashboard'
    navbar_selected_item = 'patients'
    search_form_url = 'patient_listboard_url'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            patient_add_url=self.model_cls().get_absolute_url())
        return context

    def get_queryset_filter_options(self, request, *args, **kwargs):
        options = super().get_queryset_filter_options(request, *args, **kwargs)
        if kwargs.get('subject_identifier'):
            options.update(
                {'subject_identifier': kwargs.get('subject_identifier')})
        return options

    def extra_search_options(self, search_term):
        q = Q()
        if re.match('^[A-Z]+$', search_term):
            q = Q(first_name__exact=search_term)
        return q

pharma_dashboard/templates/pharma_dashboard/buttons/dispense_button.html
<!-- {% if dispenses %}
<a href="#"
class="btn btn-sm btn-default pull-right" role="button">Refill</a>
{% endif %} -->
<a id="dispense_change_{{ subject_identifier }}" title="{{ title }}" role="button"
 href="{{ href }}"
 class="btn btn-sm btn-default pull-right" role="button">
 Dispense
</a>

pharma_dashboard/templates/pharma_dashboard/buttons/patient_button.html
    <a id="patient_change_{{ subject_identifier }}" title="{{ title }}" role="button" 
       class="btn btn-default btn-sm" href="{{ href }}"> <i class="fa fa-pencil-alt fa-sm"></i>
    </a>

pharma_dashboard/templates/pharma_dashboard/buttons/refill_button.html
{% if dispense_model_obj %}
<a id="dispense_change_{{ subject_identifier }}" title="{{ title }}" role="button"
 href="{{ href }}"
 class="btn btn-success btn-sm" role="button">
 Refill
</a>
{% endif %}

pharma_dashboard/templates/pharma_dashboard/dispensary/listboard.html
{% extends "edc_dashboard/listboard.html" %}
{% load admin_urls %}
{% load edc_base_extras %}
{% load pharma_dashboard_extras %}

             
{% block listboard_panel %}
   {% if subject_identifier %}
      <a id="dispense_add_{{subject_identifier" title="dispense" class="btn btn-sm btn-default" role="button" 
         href="{{ dispense_url }}?next=pharma_dashboard:dispense_listboard_url,subject_identifier&subject_identifier={{subject_identifier}} "> 
         <i class="fa fa-plus fa-sm"></i> Dispense
      </a>
    {% endif %}
    <a id="return_to_home" title="go back" class="btn btn-sm btn-default" role="button" 
        href="{% url patient_listboard_url %}"> <i class="fa fa-arrow-left fa-sm"></i> Go Back
    </a>
{% endblock listboard_panel %}


{% block listboard_table_header %}
    <!-- begin results header -->
    <th>#</th>
    <th></th>
    <th>Subject Identifier</th>
    <th>Initials</th>
    <th>Gender</th>
    <th>Prescription</th>
    <th>Type</th>
    <th>Prepared Date</th>
    <th>Refill On</th>
    
    <th></th>
    <!-- end results header -->
{% endblock listboard_table_header %}


{% block listboard_table_button_column %}

 <td style="white-space: nowrap">
    <div class="btn-group">
       <a id="dispense_change_{{ subject_identifier }}" title="{{ title }}" role="button" 
         class="btn btn-default btn-sm" href="{{ result.href }}"> <i class="fa fa-pencil-alt fa-sm"></i>
	   </a>
	
	    <a id="dispense_refill_{{ subject_identifier }}" title="{{ title }}" role="button"
		 href="{{ result.href }}"
		 class="btn btn-success btn-sm" role="button">
		 Refill
		</a>
     </div>
 </td>
 
{% endblock listboard_table_button_column %}


{% block listboard_table_columns %}
	<td>{{ result.object.subject_identifier }}</td>
    <td nowrap>{{ result.patient.initials }}</td>
    <td nowrap>{{ result.patient.gender }}</td>
    <td nowrap>{{ result.object.medication }}</td>
    <td nowrap>{{ result.object.dispense_type }}</td>
	<td nowrap>{{ result.object.prepared_datetime|date:"Y-m-d H:i"}}</td>
	<td nowrap>{{ result.latest_refill|date:"Y-m-d H:i"}}</td>
    <td nowrap></td>
    <td><a href="{% url 'pharma_dashboard:print_url' subject_identifier=result.object.subject_identifier dispense_pk=result.object.pk %}" class="btn btn-sm btn-default">Print</a></td>                    

{% endblock listboard_table_columns %}

pharma_dashboard/templates/pharma_dashboard/listboard.html
{% extends "edc_dashboard/listboard.html" %}
{% load admin_urls %}
{% load edc_base_extras %}
{% load pharma_dashboard_extras %}

             
{% block listboard_panel %}
    <a id="patient_add" title="add patient" class="btn btn-sm btn-default" role="button" 
        href="{{ patient_add_url }}?next={{ patient_listboard_url }}">
            <i class="fa fa-plus fa-sm"></i> Add Patient
    </a>
    <a id="return_to_home" title="go back" class="btn btn-sm btn-default" role="button" 
        href="/">
            <i class="fa fa-arrow-left fa-sm"></i> Go Back
    </a>
{% endblock listboard_panel %}


{% block listboard_table_header %}
    <!-- begin results header -->
    <th>#</th>
    <th></th>
    <th>Subject Identifier</th>
    <th>Protocol</th>
    <th>Initials</th>
    <th>Gender</th>
    <th>User</th>
    <th>Modified</th>
    <th></th>
    <!-- end results header -->
{% endblock listboard_table_header %}


{% block listboard_table_button_column %}
    <td style="white-space: nowrap">
    <div class="btn-group">
 		{% patient_button result %}
 		{% dispense_button result %}
    </div>
    </td>
    
{% endblock listboard_table_button_column %}


{% block listboard_table_columns %}
    <td nowrap>{{result.object.subject_identifier}}</td>
    <td nowrap>{{result.object.patient_site.protocol.number}}</td>
    <td nowrap>{{result.initials}}</td>
    <td nowrap>{{result.gender}}</td>
    <td nowrap>{{ result.user_created }}</td>
    <td nowrap>{{ result.object.modified|date:"SHORT_DATETIME_FORMAT" }}</td>
    <td nowrap> <a id="btn-dispensary-listboard-{{result.subject_identifier}}" class="btn btn-info btn-sm" role="button"   
        title="Dispensary Records" href="{% url dispense_listboard_url result.subject_identifier %}">
        <i class="far fa-user-circle fa-sm"></i> Dispensary Records  <i class="fa fa-share"></i></a></td>

{% endblock listboard_table_columns %}

pharma_dashboard/templates/pharma_dashboard/stock_management/listboard.html
{% extends "edc_dashboard/listboard.html" %}
{% load admin_urls %}
{% load edc_base_extras %}
{% load pharma_dashboard_extras %}

      
{% block listboard_panel %}
	<a id="stock_add" title="add patient" class="btn btn-sm btn-default" role="button" 
        href="{{ stock_add_url }}?next={{ stock_management_listboard_url }}">
            <i class="fa fa-plus fa-sm"></i> Recieve Stock
    </a>
    <a id="return_to_home" title="go back" class="btn btn-sm btn-default" role="button" 
        href="/"> <i class="fa fa-arrow-left fa-sm"></i> Go Back
    </a>
{% endblock listboard_panel %}


{% block listboard_table_header %}
    <!-- begin results header -->
    <th>#</th>
    <th></th>
    <th>Stock ID</th>
    <th>Received By</th>
    <th>Received Date</th>
    <th>Supplier</th>
    <th>Supplier Contact</th>
    <th></th>
    <th></th>
    <th></th>
    
    <th></th>
    <!-- end results header -->
{% endblock listboard_table_header %}


{% block listboard_table_button_column %}
 <td style="white-space: nowrap">
    <div class="btn-group">
  	  <a id="stock_change_{{ stock_id }}" title="{{ title }}" role="button" 
         class="btn btn-default btn-sm" href="{{ result.href }}"> <i class="fa fa-pencil-alt fa-sm"></i>
      </a>
  </div>
 </td>
    
{% endblock listboard_table_button_column %}

{{results}}
{% block listboard_table_columns %}
    <td nowrap>{{result.stock_id}}</td>
    <td nowrap>{{result.received_by}}</td>
    <td nowrap>{{result.object.received_date|date:"SHORT_DATETIME_FORMAT"}}</td>
    <td nowrap>{{result.object.supplier.name}}</td>
	<td nowrap>{{result.object.supplier.phone}}</td>
	<td nowrap></td>
    <td nowrap></td>
    <td nowrap></td>
    <td></td>                    

{% endblock listboard_table_columns %}

pharma_dashboard/templates/pharma_dashboard/stock_management/report.html
{% extends listboard_base_template %}
{% load admin_urls %}
{% load edc_base_extras %}
{% load pharma_dashboard_extras %}
{% load edc_dashboard_extras %}
{% load static %}

{% block extra-css %}
{{ block.super }}
	<link type="text/css" rel="stylesheet" href="{% static 'pharma_dashboard/css/report.css' %}">
	<link href="{% static 'pharma_dashboard/css/bootstrap-table.min.css' %}"rel=stylesheet>
{% endblock extra-css %}

{% block extra-scripts %}
{{ block.super }}
	<script src="{% static 'pharma_dashboard/js/tableExport.min.js' %}"></script>
	<script src="{% static 'pharma_dashboard/js/bootstrap-table.min.js' %}"></script>
	<script src="{% static 'pharma_dashboard/js/bootstrap-table-export.min.js' %}"></script>
	<script src="{% static 'pharma_dashboard/js/bootstrap-table-filter-control.min.js' %}"></script>
{% endblock %}
	
{% block main %}

<!-- start listboard main block-->
<div class="row">
	<div id="toolbar">
		<h3 style="font-weight:300"><img src="{% static 'pharma_dashboard/images/combo-chart.png' %}" width="40"></img> Inventory Report</h3>
	</div>
</div>
<!-- begin table -->
<div class="table table-responsive">
<table 	id="sort" class="table table-bordered table-hover small"
		data-toggle="table"
		data-toolbar="#toolbar"
		data-filter-control="true"
		data-show-columns="true"
  		data-show-columns-toggle-all="true"
		data-show-toggle="true"
		data-show-fullscreen="true"
		data-show-export="true" 
		data-pagination="true" >
<thead>

{% block listboard_table_header %}
     <!-- begin results header -->
    <th>#</th>
    <th data-field='protocol' data-sortable='true' data-filter-control="select">Protocol</th>
    <th data-field='medication' data-sortable='true' data-filter-control="input">Medication Name</th>
    <th>Remaining</th>
    <th>Average monthly consumption</th>
    <!-- end results header -->
{% endblock listboard_table_header %}

</thead><tbody>

{% block listboard_table_body %}

    {% for result in results %}
       <tr>
       
         <td>{{ forloop.counter }}</td>

          {% block listboard_table_button_column %}

          {% endblock listboard_table_button_column %}

          {% block listboard_table_columns %}
           <td nowrap>{{result.object.drug.protocol.number}}, {{result.object.drug.protocol.name}}</td>
	       <td nowrap>{{result.object.drug.name}}</td>
	       <td nowrap>
	    	 <span class="badge badge-pill badge-info">{{result.quantity}}</span>
	       </td>
	       <td nowrap>{{result.average_mothly_consumption}} {{result.object.drug.dispense_set.all.0.dispense_type|title}}s</td>
          {% endblock listboard_table_columns %}
       </tr>
    {% endfor %}

{% endblock listboard_table_body %}

</tbody></table>

<!-- begin spacer rows -->
<table>
<tr><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td></tr>
</table>
<!-- end spacer rows -->

</div><!-- end table -->

{% paginator_row %}

</div>  <!--end panel -->
</div> <!--end panel-group -->
<!-- end listboard main block -->
{% endblock main %}

pharma_dashboard/templates/pharma_dashboard/subject_record.html
{% extends 'edc_base/base.html' %}